# Generated by Django 4.2.11 on 2026-08-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_proyectos', '0003_alter_proyecto_descripcion_alter_proyecto_duracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='imagen',
            field=models.ImageField(default='img/logo.png', upload_to='img/'),
        ),
    ]
